# -*- coding: utf-8 -*-
"""Cosine_Similarity_Mathematically.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfiLd9gISUkSXZl_GLHg6aN3_v_iekgQ
"""

vector_A = [2, 4, 1]
vector_B = [1, 3, 5]

print("Vector A:", vector_A)
print("Vector B:", vector_B)

def dot_product(A, B):
    total = 0
    for a, b in zip(A, B):
        total += a * b
    return total

dp = dot_product(vector_A, vector_B)
print("Dot Product (A . B):", dp)

import math

def magnitude(A):
    total = 0
    for a in A:
        total += a ** 2
    return math.sqrt(total)

mag_A = magnitude(vector_A)
mag_B = magnitude(vector_B)

print("Magnitude of A:", round(mag_A, 4))
print("Magnitude of B:", round(mag_B, 4))

def cosine_similarity_manual(A, B):
    dp = dot_product(A, B)
    mag_A = magnitude(A)
    mag_B = magnitude(B)
    similarity = dp / (mag_A * mag_B)
    return similarity

result_manual = cosine_similarity_manual(vector_A, vector_B)
print("Cosine Similarity (Manual Calculation):", round(result_manual, 4))

import numpy as np

A = np.array(vector_A)
B = np.array(vector_B)

dot = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

result_numpy = dot / (norm_A * norm_B)
print("Cosine Similarity (NumPy):", round(result_numpy, 4))

!pip install -q scikit-learn

from sklearn.metrics.pairwise import cosine_similarity

# sklearn expects 2D arrays: shape (1, n)
A_2d = np.array(vector_A).reshape(1, -1)
B_2d = np.array(vector_B).reshape(1, -1)

result_sklearn = cosine_similarity(A_2d, B_2d)[0][0]
print("Cosine Similarity (scikit-learn):", round(result_sklearn, 4))

print("Manual     :", round(result_manual, 6))
print("NumPy      :", round(result_numpy, 6))
print("scikit-learn:", round(result_sklearn, 6))

assert round(result_manual, 4) == round(result_numpy, 4) == round(result_sklearn, 4)
print("\nAll three methods match!")

examples = {
    "Identical vectors": ([1, 2, 3], [1, 2, 3]),
    "Opposite vectors": ([1, 2, 3], [-1, -2, -3]),
    "Perpendicular vectors": ([1, 0], [0, 1]),
    "Scaled vectors (same direction)": ([1, 2, 3], [2, 4, 6]),
}

for name, (a, b) in examples.items():
    sim = cosine_similarity_manual(a, b)
    print(f"{name:35s} -> {round(sim, 4)}")