# -*- coding: utf-8 -*-
"""HuggingFace_Embeddings_Scratch_to_Intermediate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRCgJ8mSUGN5o3hE1JTJwgiF-6dwBjEo
"""

!pip install -q sentence-transformers scikit-learn matplotlib

from sentence_transformers import SentenceTransformer
# Load the free pre-trained model from Hugging Face
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully!")

sentence = "I love learning about Artificial Intelligence."
embedding = model.encode(sentence)
print("Sentence:", sentence)
print("Embedding shape:", embedding.shape)
print("First 10 values:", embedding[:10])

sentences = [
    "I love dogs",
    "I like puppies",
    "The stock market crashed today",
    "Cats are cute pets",
    "The economy is in recession"
]
embeddings = model.encode(sentences)
print("Number of sentences:", len(sentences))
print("Embedding matrix shape:", embeddings.shape)

from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(embeddings)
import pandas as pd
df = pd.DataFrame(similarity_matrix, index=sentences, columns=sentences)
df.round(2)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
reduced = pca.fit_transform(embeddings)

plt.figure(figsize=(7, 5))
plt.scatter(reduced[:, 0], reduced[:, 1])

for i, sent in enumerate(sentences):
    plt.annotate(sent, (reduced[i, 0], reduced[i, 1]), fontsize=9)

plt.title("2D Visualization of Sentence Embeddings")
plt.xlabel("PCA Dimension 1")
plt.ylabel("PCA Dimension 2")
plt.grid(True)
plt.show()

# Our small "document" database
documents = [
    "Python is a popular programming language for AI.",
    "The weather today is sunny and warm.",
    "Machine learning models learn patterns from data.",
    "I enjoy playing football on weekends.",
    "Deep learning uses neural networks with many layers.",
    "Paris is the capital city of France."
]

# Encode all documents once
doc_embeddings = model.encode(documents)

def semantic_search(query, top_k=2):
    query_embedding = model.encode([query])
    scores = cosine_similarity(query_embedding, doc_embeddings)[0]
    # Rank documents by similarity score
    ranked_idx = scores.argsort()[::-1][:top_k]
    print(f"Query: {query}\n")
    for idx in ranked_idx:
        print(f"Score: {scores[idx]:.3f}  |  {documents[idx]}")

# Try it
semantic_search("Tell me about AI and neural networks")

# Try another query
semantic_search("What is the capital of France?")