# -*- coding: utf-8 -*-
"""word_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pqhUycKKwJ2bTw7jHOEhDGcK0-DyHrH

Word Embedding using One-Hot Encoding
"""

from sklearn.preprocessing import OneHotEncoder

words = [['cat'],['dog'],['apple'],['car']]

encoder = OneHotEncoder(sparse_output=False)
result = encoder.fit_transform(words)

print("words :",encoder.categories_[0])
print("Embeddings:")
print(result)

"""['apple' 'car' 'cat' 'dog']
['apple' 'car' 'cat' 'dog']
['apple' 'car' 'cat' 'dog']
['apple' 'car' 'cat' 'dog']

Find Similar Words using Word2Vec
"""

!pip install gensim

from gensim.models import Word2Vec

sentences = [["python","is","a","language"],
 ["java","is","a","language"],
  ["python","is","easy"],
   ["java","is","easy"],
    ["python","is","powerful"],
     ["java","is","powerful"]]

model = Word2Vec(sentences,vector_size=10,window=2,min_count=1,workers=1)

print(model.wv.most_similar('java',topn=3))

print(model.wv.most_similar('python',topn=4))